# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
# paginate: 2 # jekyll-paginate > items per page
# paginate_path: blog/page:num # jekyll-paginate > blog page
author: STAMPS 2019 Team 

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 5. Collections
# collections:
#   posts:
#     title: Posts # Needed for Siteleaf
#     output: true
#     description: "My thoughts and ideas" # The post list page content
#     feature_text: |
#       Welcome to the blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "MBL STAMPS 2019" # Site name or title, also used in jekyll-seo-tag
logo: "/images/uchicago-mbl.png" # Site logo, also used in jekyll-seo-tag
description: "Home page for the STAMPS 2019 course."
# url: "https://alembic.darn.es" # Site url, also used in jekyll-seo-tag
baseurl: ""
# repo: "https://github.com/daviddarnes/alembic"
# email: "me@daviddarnes.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# avatarurl: "/images/MBL-logo.jpg" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
# navigation_header:
#   Schedule: /
#   Elements: /elements/

navigation_footer:
  "Hosted by GitHub Pages;": https://pages.github.com/
  Built from the Alembic template: https://github.com/daviddarnes/alembic

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  # Twitter: "#0d94e7"
  # facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
